fix: Get header version from URL instead of theme.conf
ROCm/rocm-docs-core pull request #769
Opened 2024-05-09 18:20 UTC by samjwu

2024-05-15 21:33 UTC, saadrahim commented
How does latest know what version it is?

2024-05-15 22:43 UTC, samjwu commented
> How does latest know what version it is?

It grabs it from a file in the header-versions branch https://github.com/ROCm/rocm-docs-core/blob/header-versions/latest_version.txt

2024-05-15 22:45 UTC, saadrahim requested changes
I don't think this approach is suitable for offline environments.

2024-05-15 22:45 UTC, saadrahim commented on src/rocm_docs/theme.py
> +        "https://raw.githubusercontent.com/RadeonOpenCompute/rocm-docs-core/header-versions/latest_version.txt"
change the org to ROCm

2024-05-15 22:45 UTC, saadrahim commented on src/rocm_docs/theme.py
> +        "https://raw.githubusercontent.com/RadeonOpenCompute/rocm-docs-core/header-versions/release_candidate.txt"
ROCm

2024-05-15 23:07 UTC, samjwu commented
> I don't think this approach is suitable for offline environments.

No, but offline build functionality is also currently blocked by other features such as intersphinx

2024-05-22 20:14 UTC, yhuiYH approved these changes
OK, approved

2024-05-22 22:38 UTC, merged